// flow-typed signature: 06b29bb61441bd799999e23bbbb31199
// flow-typed version: <<STUB>>/bpk-tokens_v^27.4.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bpk-tokens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bpk-tokens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bpk-tokens/formatters/adjust-typography' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.android.xml' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.common.js' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.default.scss' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.es6.js' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.ios.json' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.raw.json' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.react.native.common.js' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.react.native.es6.js' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/bpk.scss' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/license-header' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/react-native-value-template' {
  declare module.exports: any;
}

declare module 'bpk-tokens/formatters/sort-tokens' {
  declare module.exports: any;
}

declare module 'bpk-tokens/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'bpk-tokens/src/react-native-output-test' {
  declare module.exports: any;
}

declare module 'bpk-tokens/src/setOpacity-test' {
  declare module.exports: any;
}

declare module 'bpk-tokens/src/setOpacity' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/android/base.react.native.common' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/android/base.react.native.es6' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/b2b-widgets.common' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/b2b-widgets.es6' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/base.common' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/base.es6' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/base.react.native.android' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/base.react.native.ios' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/breakpoints.common' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/breakpoints.es6' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/ios/base.react.native.common' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/ios/base.react.native.es6' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/travelpro.common' {
  declare module.exports: any;
}

declare module 'bpk-tokens/tokens/travelpro.es6' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bpk-tokens/formatters/adjust-typography.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/adjust-typography'>;
}
declare module 'bpk-tokens/formatters/bpk.android.xml.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.android.xml'>;
}
declare module 'bpk-tokens/formatters/bpk.common.js.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.common.js'>;
}
declare module 'bpk-tokens/formatters/bpk.default.scss.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.default.scss'>;
}
declare module 'bpk-tokens/formatters/bpk.es6.js.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.es6.js'>;
}
declare module 'bpk-tokens/formatters/bpk.ios.json.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.ios.json'>;
}
declare module 'bpk-tokens/formatters/bpk.raw.json.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.raw.json'>;
}
declare module 'bpk-tokens/formatters/bpk.react.native.common.js.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.react.native.common.js'>;
}
declare module 'bpk-tokens/formatters/bpk.react.native.es6.js.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.react.native.es6.js'>;
}
declare module 'bpk-tokens/formatters/bpk.scss.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/bpk.scss'>;
}
declare module 'bpk-tokens/formatters/license-header.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/license-header'>;
}
declare module 'bpk-tokens/formatters/react-native-value-template.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/react-native-value-template'>;
}
declare module 'bpk-tokens/formatters/sort-tokens.js' {
  declare module.exports: $Exports<'bpk-tokens/formatters/sort-tokens'>;
}
declare module 'bpk-tokens/gulpfile.babel.js' {
  declare module.exports: $Exports<'bpk-tokens/gulpfile.babel'>;
}
declare module 'bpk-tokens/index' {
  declare module.exports: $Exports<'bpk-tokens'>;
}
declare module 'bpk-tokens/index.js' {
  declare module.exports: $Exports<'bpk-tokens'>;
}
declare module 'bpk-tokens/src/react-native-output-test.js' {
  declare module.exports: $Exports<'bpk-tokens/src/react-native-output-test'>;
}
declare module 'bpk-tokens/src/setOpacity-test.js' {
  declare module.exports: $Exports<'bpk-tokens/src/setOpacity-test'>;
}
declare module 'bpk-tokens/src/setOpacity.js' {
  declare module.exports: $Exports<'bpk-tokens/src/setOpacity'>;
}
declare module 'bpk-tokens/tokens/android/base.react.native.common.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/android/base.react.native.common'>;
}
declare module 'bpk-tokens/tokens/android/base.react.native.es6.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/android/base.react.native.es6'>;
}
declare module 'bpk-tokens/tokens/b2b-widgets.common.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/b2b-widgets.common'>;
}
declare module 'bpk-tokens/tokens/b2b-widgets.es6.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/b2b-widgets.es6'>;
}
declare module 'bpk-tokens/tokens/base.common.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/base.common'>;
}
declare module 'bpk-tokens/tokens/base.es6.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/base.es6'>;
}
declare module 'bpk-tokens/tokens/base.react.native.android.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/base.react.native.android'>;
}
declare module 'bpk-tokens/tokens/base.react.native.ios.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/base.react.native.ios'>;
}
declare module 'bpk-tokens/tokens/breakpoints.common.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/breakpoints.common'>;
}
declare module 'bpk-tokens/tokens/breakpoints.es6.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/breakpoints.es6'>;
}
declare module 'bpk-tokens/tokens/ios/base.react.native.common.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/ios/base.react.native.common'>;
}
declare module 'bpk-tokens/tokens/ios/base.react.native.es6.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/ios/base.react.native.es6'>;
}
declare module 'bpk-tokens/tokens/travelpro.common.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/travelpro.common'>;
}
declare module 'bpk-tokens/tokens/travelpro.es6.js' {
  declare module.exports: $Exports<'bpk-tokens/tokens/travelpro.es6'>;
}
