// flow-typed signature: a4a6eb960f7844610284b30c819b3154
// flow-typed version: <<STUB>>/eslint-config-skyscanner-with-prettier_v^0.8.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-skyscanner-with-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-skyscanner-with-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-skyscanner-with-prettier/main' {
  declare module.exports: any;
}

declare module 'eslint-config-skyscanner-with-prettier/test/bpk-token-fail' {
  declare module.exports: any;
}

declare module 'eslint-config-skyscanner-with-prettier/test/jsdoc-fail' {
  declare module.exports: any;
}

declare module 'eslint-config-skyscanner-with-prettier/test/pass' {
  declare module.exports: any;
}

declare module 'eslint-config-skyscanner-with-prettier/test/prettier-fail' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-skyscanner-with-prettier/index' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier'>;
}
declare module 'eslint-config-skyscanner-with-prettier/index.js' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier'>;
}
declare module 'eslint-config-skyscanner-with-prettier/main.js' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier/main'>;
}
declare module 'eslint-config-skyscanner-with-prettier/test/bpk-token-fail.jsx' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier/test/bpk-token-fail'>;
}
declare module 'eslint-config-skyscanner-with-prettier/test/jsdoc-fail.js' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier/test/jsdoc-fail'>;
}
declare module 'eslint-config-skyscanner-with-prettier/test/pass.jsx' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier/test/pass'>;
}
declare module 'eslint-config-skyscanner-with-prettier/test/prettier-fail.jsx' {
  declare module.exports: $Exports<'eslint-config-skyscanner-with-prettier/test/prettier-fail'>;
}
