// flow-typed signature: 399f17437d262f843c7ab5f8601a60f8
// flow-typed version: <<STUB>>/eslint_d_v^7.2.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint_d'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint_d' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint_d/bin/eslint_d' {
  declare module.exports: any;
}

declare module 'eslint_d/bin/eslint' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/client' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/connect' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/daemon' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/launcher' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/linter' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/options' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/out' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/portfile' {
  declare module.exports: any;
}

declare module 'eslint_d/lib/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint_d/bin/eslint_d.js' {
  declare module.exports: $Exports<'eslint_d/bin/eslint_d'>;
}
declare module 'eslint_d/bin/eslint.js' {
  declare module.exports: $Exports<'eslint_d/bin/eslint'>;
}
declare module 'eslint_d/lib/client.js' {
  declare module.exports: $Exports<'eslint_d/lib/client'>;
}
declare module 'eslint_d/lib/connect.js' {
  declare module.exports: $Exports<'eslint_d/lib/connect'>;
}
declare module 'eslint_d/lib/daemon.js' {
  declare module.exports: $Exports<'eslint_d/lib/daemon'>;
}
declare module 'eslint_d/lib/launcher.js' {
  declare module.exports: $Exports<'eslint_d/lib/launcher'>;
}
declare module 'eslint_d/lib/linter.js' {
  declare module.exports: $Exports<'eslint_d/lib/linter'>;
}
declare module 'eslint_d/lib/options.js' {
  declare module.exports: $Exports<'eslint_d/lib/options'>;
}
declare module 'eslint_d/lib/out.js' {
  declare module.exports: $Exports<'eslint_d/lib/out'>;
}
declare module 'eslint_d/lib/portfile.js' {
  declare module.exports: $Exports<'eslint_d/lib/portfile'>;
}
declare module 'eslint_d/lib/server.js' {
  declare module.exports: $Exports<'eslint_d/lib/server'>;
}
