// flow-typed signature: 124399669649e5b48fc72d885869b8e7
// flow-typed version: <<STUB>>/react-native-linear-gradient_vreact-native-community/react-native-linear-gradient#20928ce2ac8038e8545c7f6c3faab05f866deabd/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-linear-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-linear-gradient/index.android' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.windows' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/nativeLinearGradient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-linear-gradient/index.android.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.android'>;
}
declare module 'react-native-linear-gradient/index.ios.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.ios'>;
}
declare module 'react-native-linear-gradient/index' {
  declare module.exports: $Exports<'react-native-linear-gradient'>;
}
declare module 'react-native-linear-gradient/index.js' {
  declare module.exports: $Exports<'react-native-linear-gradient'>;
}
declare module 'react-native-linear-gradient/index.windows.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.windows'>;
}
declare module 'react-native-linear-gradient/nativeLinearGradient.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/nativeLinearGradient'>;
}
