source 'https://cdn.cocoapods.org/'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
use_frameworks!

target 'Backpack Native' do

  use_react_native!(
    # :path => '../node_modules/react-native',
    :hermes_enabled => false,
  )

  # All these libraries below have been removed from the Xcode project file and now live in the Podfile. Cocoapods handles the linking now. Here you can add more libraries with native modules.
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector", :modular_headers => true
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec", :modular_headers => true
  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec', :modular_headers => false
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired", :modular_headers => true
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety", :modular_headers => true
  pod 'React', :path => '../node_modules/react-native/', :modular_headers => false
  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules', :modular_headers => true
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/', :modular_headers => true
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS', :modular_headers => false
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation', :modular_headers => false
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob', :modular_headers => false
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image', :modular_headers => false
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS', :modular_headers => false
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network', :modular_headers => false
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings', :modular_headers => false
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => false
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration', :modular_headers => false
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/', :modular_headers => true
  # pod 'React-bridging', :path => '../node_modules/react-native/ReactCommon/React-bridging.podspec', :modular_headers => false
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact', :modular_headers => false
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => false
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor', :modular_headers => false
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector', :modular_headers => false
  pod 'React-logger', :path => '../node_modules/react-native/ReactCommon/logger', :modular_headers => false
  pod 'React-perflogger', :path => '../node_modules/react-native/ReactCommon/reactperflogger', :modular_headers => false
  pod 'React-runtimeexecutor', :path => '../node_modules/react-native/ReactCommon/runtimeexecutor', :modular_headers => false
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker", :modular_headers => false
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon", :modular_headers => false
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => false
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec', :modular_headers => false
  # pod 'React-Codegen', :path => 'build/generated/ios', :modular_headers => false
  
  # RN Bridging Pods
  pod 'Backpack', :modular_headers => true
  pod 'BackpackReactNative', path: '../node_modules/backpack-react-native/ios/BackpackReactNative', :modular_headers => false

  # Third party pods
  pod 'react-native-maps', path: '../node_modules/react-native-maps', :modular_headers => false

  target 'Backpack Native Tests' do
    inherit! :complete
  end

  use_native_modules!

    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    # :hermes_enabled => false,
    # :fabric_enabled => flags[:fabric_enabled],
    # # An absolute path to your application root.
    # :app_path => "#{Pod::Config.instance.installation_root}/.."

  post_install do |installer|
    # react_native_post_install(installer)
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Solution from https://github.com/facebook/react-native/issues/31034#issuecomment-812564390
    # Works around an issue in FBReactNativeSpec where "Generate Specs" should be before "Headers" but isn't
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end

      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end
