/*
 * Backpack - Skyscanner's Design System
 *
 * Copyright 2016-2021 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* @flow */

export type BpkDynamicValue<T> = { light: T, dark: T };

// prettier does't handle this well
// prettier-ignore
export type UnpackedBpkDynamicValue<X> = $Call<
  & ((string | BpkDynamicValue<string>) => string)
  & ((number | BpkDynamicValue<number>) => number)
  & ((boolean | BpkDynamicValue<boolean>) => boolean)
  & ((Array<string> | BpkDynamicValue<Array<string>>) => Array<string>)
  & ((Array<number> | BpkDynamicValue<Array<number>>) => Array<number>)
  & ((Array<boolean> | BpkDynamicValue<Array<boolean>>) => Array<boolean>)
  & ((any | BpkDynamicValue<*>) => any)
  & ((*) => X),
  X
>;

/**
 * Extract the original type for all react style props and enhance it BpkDynamicValue
 * The resulting type is all props accepting their original type or BpkDynamicValue<{original type}>
 *
 * E.g.
 *  Before: color: string | null
 *  After: color: string | null | BpkDynamicValue<string | null>
 *
 * This should be used alogside with $Call, E.g. $Call<BpkDynamicStyleSheetTypeEnhancer, AllReactStyleProps>
 */
// prettier-ignore
export type BpkDynamicStyleSheetTypeEnhancer =
  <
    ALIGNCONTENT,
    ALIGNITEMS,
    ALIGNSELF,
    ASPECTRATIO,
    BACKFACEVISIBILITY,
    BACKGROUNDCOLOR,
    BORDERBOTTOMCOLOR,
    BORDERBOTTOMLEFTRADIUS,
    BORDERBOTTOMRIGHTRADIUS,
    BORDERBOTTOMWIDTH,
    BORDERCOLOR,
    BORDERENDCOLOR,
    BORDERLEFTCOLOR,
    BORDERLEFTWIDTH,
    BORDERRADIUS,
    BORDERRIGHTCOLOR,
    BORDERRIGHTWIDTH,
    BORDERSTARTCOLOR,
    BORDERSTYLE,
    BORDERTOPCOLOR,
    BORDERTOPLEFTRADIUS,
    BORDERTOPRIGHTRADIUS,
    BORDERTOPWIDTH,
    BORDERWIDTH,
    BOTTOM,
    COLOR,
    DIRECTION,
    DISPLAY,
    ELEVATION,
    FLEX,
    FLEXBASIS,
    FLEXDIRECTION,
    FLEXGROW,
    FLEXSHRINK,
    FLEXWRAP,
    FONTFAMILY,
    FONTSIZE,
    FONTSTYLE,
    FONTVARIANT,
    FONTWEIGHT,
    HEIGHT,
    INCLUDEFONTPADDING,
    JUSTIFYCONTENT,
    LEFT,
    LETTERSPACING,
    LINEHEIGHT,
    MARGIN,
    MARGINBOTTOM,
    MARGINHORIZONTAL,
    MARGINLEFT,
    MARGINRIGHT,
    MARGINTOP,
    MARGINVERTICAL,
    MAXHEIGHT,
    MAXWIDTH,
    MINHEIGHT,
    MINWIDTH,
    OPACITY,
    OVERFLOW,
    OVERLAYCOLOR,
    PADDING,
    PADDINGBOTTOM,
    PADDINGHORIZONTAL,
    PADDINGLEFT,
    PADDINGRIGHT,
    PADDINGTOP,
    PADDINGVERTICAL,
    POSITION,
    RESIZEMODE,
    RIGHT,
    SHADOWCOLOR,
    SHADOWOFFSET,
    SHADOWOPACITY,
    SHADOWRADIUS,
    TEXTALIGN,
    TEXTALIGNVERTICAL,
    TEXTDECORATIONCOLOR,
    TEXTDECORATIONLINE,
    TEXTDECORATIONSTYLE,
    TEXTSHADOWCOLOR,
    TEXTSHADOWOFFSET,
    TEXTSHADOWRADIUS,
    TINTCOLOR,
    TOP,
    TRANSFORM,
    WIDTH,
    WRITINGDIRECTION,
    ZINDEX,
  >({
    alignContent: ALIGNCONTENT,
    alignItems: ALIGNITEMS,
    alignSelf: ALIGNSELF,
    aspectRatio: ASPECTRATIO,
    backfaceVisibility: BACKFACEVISIBILITY,
    backgroundColor: BACKGROUNDCOLOR,
    borderBottomColor: BORDERBOTTOMCOLOR,
    borderBottomLeftRadius: BORDERBOTTOMLEFTRADIUS,
    borderBottomRightRadius: BORDERBOTTOMRIGHTRADIUS,
    borderBottomWidth: BORDERBOTTOMWIDTH,
    borderColor: BORDERCOLOR,
    borderEndColor: BORDERENDCOLOR,
    borderLeftColor: BORDERLEFTCOLOR,
    borderLeftWidth: BORDERLEFTWIDTH,
    borderRadius: BORDERRADIUS,
    borderRightColor: BORDERRIGHTCOLOR,
    borderRightWidth: BORDERRIGHTWIDTH,
    borderStartColor: BORDERSTARTCOLOR,
    borderStyle: BORDERSTYLE,
    borderTopColor: BORDERTOPCOLOR,
    borderTopLeftRadius: BORDERTOPLEFTRADIUS,
    borderTopRightRadius: BORDERTOPRIGHTRADIUS,
    borderTopWidth: BORDERTOPWIDTH,
    borderWidth: BORDERWIDTH,
    bottom: BOTTOM,
    color: COLOR,
    direction: DIRECTION,
    display: DISPLAY,
    elevation: ELEVATION,
    flex: FLEX,
    flexBasis: FLEXBASIS,
    flexDirection: FLEXDIRECTION,
    flexGrow: FLEXGROW,
    flexShrink: FLEXSHRINK,
    flexWrap: FLEXWRAP,
    fontFamily: FONTFAMILY,
    fontSize: FONTSIZE,
    fontStyle: FONTSTYLE,
    fontVariant: FONTVARIANT,
    fontWeight: FONTWEIGHT,
    height: HEIGHT,
    includeFontPadding: INCLUDEFONTPADDING,
    justifyContent: JUSTIFYCONTENT,
    left: LEFT,
    letterSpacing: LETTERSPACING,
    lineHeight: LINEHEIGHT,
    margin: MARGIN,
    marginBottom: MARGINBOTTOM,
    marginHorizontal: MARGINHORIZONTAL,
    marginLeft: MARGINLEFT,
    marginRight: MARGINRIGHT,
    marginTop: MARGINTOP,
    marginVertical: MARGINVERTICAL,
    maxHeight: MAXHEIGHT,
    maxWidth: MAXWIDTH,
    minHeight: MINHEIGHT,
    minWidth: MINWIDTH,
    opacity: OPACITY,
    overflow: OVERFLOW,
    overlayColor: OVERLAYCOLOR,
    padding: PADDING,
    paddingBottom: PADDINGBOTTOM,
    paddingHorizontal: PADDINGHORIZONTAL,
    paddingLeft: PADDINGLEFT,
    paddingRight: PADDINGRIGHT,
    paddingTop: PADDINGTOP,
    paddingVertical: PADDINGVERTICAL,
    position: POSITION,
    resizeMode: RESIZEMODE,
    right: RIGHT,
    shadowColor: SHADOWCOLOR,
    shadowOffset: SHADOWOFFSET,
    shadowOpacity: SHADOWOPACITY,
    shadowRadius: SHADOWRADIUS,
    textAlign: TEXTALIGN,
    textAlignVertical: TEXTALIGNVERTICAL,
    textDecorationColor: TEXTDECORATIONCOLOR,
    textDecorationLine: TEXTDECORATIONLINE,
    textDecorationStyle: TEXTDECORATIONSTYLE,
    textShadowColor: TEXTSHADOWCOLOR,
    textShadowOffset: TEXTSHADOWOFFSET,
    textShadowRadius: TEXTSHADOWRADIUS,
    tintColor: TINTCOLOR,
    top: TOP,
    transform: TRANSFORM,
    width: WIDTH,
    writingDirection: WRITINGDIRECTION,
    zIndex: ZINDEX,
  }) => {
    alignContent?: ALIGNCONTENT | BpkDynamicValue<ALIGNCONTENT>,
    alignItems?: ALIGNITEMS | BpkDynamicValue<ALIGNITEMS>,
    alignSelf?: ALIGNSELF | BpkDynamicValue<ALIGNSELF>,
    aspectRatio?: ASPECTRATIO | BpkDynamicValue<ASPECTRATIO>,
    backfaceVisibility?: BACKFACEVISIBILITY | BpkDynamicValue<BACKFACEVISIBILITY>,
    backgroundColor?: BACKGROUNDCOLOR | BpkDynamicValue<BACKGROUNDCOLOR>,
    borderBottomColor?: BORDERBOTTOMCOLOR | BpkDynamicValue<BORDERBOTTOMCOLOR>,
  borderBottomLeftRadius?: | BORDERBOTTOMLEFTRADIUS
    | BpkDynamicValue<BORDERBOTTOMLEFTRADIUS>,
  borderBottomRightRadius?: | BORDERBOTTOMRIGHTRADIUS
    | BpkDynamicValue<BORDERBOTTOMRIGHTRADIUS>,
  borderBottomWidth?: BORDERBOTTOMWIDTH | BpkDynamicValue<BORDERBOTTOMWIDTH>,
  borderColor?: BORDERCOLOR | BpkDynamicValue<BORDERCOLOR>,
  borderEndColor?: BORDERENDCOLOR | BpkDynamicValue<BORDERENDCOLOR>,
  borderLeftColor?: BORDERLEFTCOLOR | BpkDynamicValue<BORDERLEFTCOLOR>,
  borderLeftWidth?: BORDERLEFTWIDTH | BpkDynamicValue<BORDERLEFTWIDTH>,
  borderRadius?: BORDERRADIUS | BpkDynamicValue<BORDERRADIUS>,
  borderRightColor?: BORDERRIGHTCOLOR | BpkDynamicValue<BORDERRIGHTCOLOR>,
  borderRightWidth?: BORDERRIGHTWIDTH | BpkDynamicValue<BORDERRIGHTWIDTH>,
  borderStartColor?: BORDERSTARTCOLOR | BpkDynamicValue<BORDERSTARTCOLOR>,
  borderStyle?: BORDERSTYLE | BpkDynamicValue<BORDERSTYLE>,
  borderTopColor?: BORDERTOPCOLOR | BpkDynamicValue<BORDERTOPCOLOR>,
  borderTopLeftRadius?: | BORDERTOPLEFTRADIUS
    | BpkDynamicValue<BORDERTOPLEFTRADIUS>,
  borderTopRightRadius?: | BORDERTOPRIGHTRADIUS
    | BpkDynamicValue<BORDERTOPRIGHTRADIUS>,
  borderTopWidth?: BORDERTOPWIDTH | BpkDynamicValue<BORDERTOPWIDTH>,
  borderWidth?: BORDERWIDTH | BpkDynamicValue<BORDERWIDTH>,
  bottom?: BOTTOM | BpkDynamicValue<BOTTOM>,
  color?: COLOR | BpkDynamicValue<COLOR>,
  direction?: DIRECTION | BpkDynamicValue<DIRECTION>,
  display?: DISPLAY | BpkDynamicValue<DISPLAY>,
  elevation?: ELEVATION | BpkDynamicValue<ELEVATION>,
  flex?: FLEX | BpkDynamicValue<FLEX>,
  flexBasis?: FLEXBASIS | BpkDynamicValue<FLEXBASIS>,
  flexDirection?: FLEXDIRECTION | BpkDynamicValue<FLEXDIRECTION>,
  flexGrow?: FLEXGROW | BpkDynamicValue<FLEXGROW>,
  flexShrink?: FLEXSHRINK | BpkDynamicValue<FLEXSHRINK>,
  flexWrap?: FLEXWRAP | BpkDynamicValue<FLEXWRAP>,
  fontFamily?: FONTFAMILY | BpkDynamicValue<FONTFAMILY>,
  fontSize?: FONTSIZE | BpkDynamicValue<FONTSIZE>,
  fontStyle?: FONTSTYLE | BpkDynamicValue<FONTSTYLE>,
  fontVariant?: FONTVARIANT | BpkDynamicValue<FONTVARIANT>,
  fontWeight?: FONTWEIGHT | BpkDynamicValue<FONTWEIGHT>,
  height?: HEIGHT | BpkDynamicValue<HEIGHT>,
  includeFontPadding?: INCLUDEFONTPADDING | BpkDynamicValue<INCLUDEFONTPADDING>,
  justifyContent?: JUSTIFYCONTENT | BpkDynamicValue<JUSTIFYCONTENT>,
  left?: LEFT | BpkDynamicValue<LEFT>,
  letterSpacing?: LETTERSPACING | BpkDynamicValue<LETTERSPACING>,
  lineHeight?: LINEHEIGHT | BpkDynamicValue<LINEHEIGHT>,
  margin?: MARGIN | BpkDynamicValue<MARGIN>,
  marginBottom?: MARGINBOTTOM | BpkDynamicValue<MARGINBOTTOM>,
  marginHorizontal?: MARGINHORIZONTAL | BpkDynamicValue<MARGINHORIZONTAL>,
  marginLeft?: MARGINLEFT | BpkDynamicValue<MARGINLEFT>,
  marginRight?: MARGINRIGHT | BpkDynamicValue<MARGINRIGHT>,
  marginTop?: MARGINTOP | BpkDynamicValue<MARGINTOP>,
  marginVertical?: MARGINVERTICAL | BpkDynamicValue<MARGINVERTICAL>,
  maxHeight?: MAXHEIGHT | BpkDynamicValue<MAXHEIGHT>,
  maxWidth?: MAXWIDTH | BpkDynamicValue<MAXWIDTH>,
  minHeight?: MINHEIGHT | BpkDynamicValue<MINHEIGHT>,
  minWidth?: MINWIDTH | BpkDynamicValue<MINWIDTH>,
  opacity?: OPACITY | BpkDynamicValue<OPACITY>,
  overflow?: OVERFLOW | BpkDynamicValue<OVERFLOW>,
  overlayColor?: OVERLAYCOLOR | BpkDynamicValue<OVERLAYCOLOR>,
  padding?: PADDING | BpkDynamicValue<PADDING>,
  paddingBottom?: PADDINGBOTTOM | BpkDynamicValue<PADDINGBOTTOM>,
  paddingHorizontal?: PADDINGHORIZONTAL | BpkDynamicValue<PADDINGHORIZONTAL>,
  paddingLeft?: PADDINGLEFT | BpkDynamicValue<PADDINGLEFT>,
  paddingRight?: PADDINGRIGHT | BpkDynamicValue<PADDINGRIGHT>,
  paddingTop?: PADDINGTOP | BpkDynamicValue<PADDINGTOP>,
  paddingVertical?: PADDINGVERTICAL | BpkDynamicValue<PADDINGVERTICAL>,
  position?: POSITION | BpkDynamicValue<POSITION>,
  resizeMode?: RESIZEMODE | BpkDynamicValue<RESIZEMODE>,
  right?: RIGHT | BpkDynamicValue<RIGHT>,
  shadowColor?: SHADOWCOLOR | BpkDynamicValue<SHADOWCOLOR>,
  shadowOffset?: SHADOWOFFSET | BpkDynamicValue<SHADOWOFFSET>,
  shadowOpacity?: SHADOWOPACITY | BpkDynamicValue<SHADOWOPACITY>,
  shadowRadius?: SHADOWRADIUS | BpkDynamicValue<SHADOWRADIUS>,
  textAlign?: TEXTALIGN | BpkDynamicValue<TEXTALIGN>,
  textAlignVertical?: TEXTALIGNVERTICAL | BpkDynamicValue<TEXTALIGNVERTICAL>,
  textDecorationColor?: | TEXTDECORATIONCOLOR
    | BpkDynamicValue<TEXTDECORATIONCOLOR>,
  textDecorationLine?: TEXTDECORATIONLINE | BpkDynamicValue<TEXTDECORATIONLINE>,
  textDecorationStyle?: | TEXTDECORATIONSTYLE
    | BpkDynamicValue<TEXTDECORATIONSTYLE>,
  textShadowColor?: TEXTSHADOWCOLOR | BpkDynamicValue<TEXTSHADOWCOLOR>,
  textShadowOffset?: TEXTSHADOWOFFSET | BpkDynamicValue<TEXTSHADOWOFFSET>,
  textShadowRadius?: TEXTSHADOWRADIUS | BpkDynamicValue<TEXTSHADOWRADIUS>,
  tintColor?: TINTCOLOR | BpkDynamicValue<TINTCOLOR>,
  top?: TOP | BpkDynamicValue<TOP>,
  transform?: TRANSFORM | BpkDynamicValue<TRANSFORM>,
  width?: WIDTH | BpkDynamicValue<WIDTH>,
  writingDirection?: WRITINGDIRECTION | BpkDynamicValue<WRITINGDIRECTION>,
  zIndex?: ZINDEX | BpkDynamicValue<ZINDEX>,
};
