# This workflow should run post the Android and iOS CI passing - which would trigger a docs deployment
name: Deploy docs

on:
  workflow_run:
    workflows: ["Android CI", "iOS CI"]
    branches: [master]
    types: 
      - completed

defaults:
  run:
    shell: bash -l {0}

jobs:
  trigger_docs:
    name: Trigger docs build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger docs build
        env:
          BACKPACK_DOCS_DEPLOY_TOKEN: ${{ secrets.BACKPACK_DOCS_DEPLOY_TOKEN }}
        run: |
          curl -f -s -X POST -H "Content-Type: application/json" -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $BACKPACK_DOCS_DEPLOY_TOKEN" -d '{"ref":"master","inputs":{"repo":"backpack-react-native"}}' https://api.github.com/repos/Skyscanner/backpack-docs/actions/workflows/ci.yml/dispatches