name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash -l {0}

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NPM
        run: |
          nvm install
          npm ci

      - name: Run tests
        run: npm test
